package Model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * AutorDetalls generated by hbm2java
 */
@Entity
@Table(name = "AutorDetalls", catalog = "autors")
public class AutorDetalls implements java.io.Serializable {

	private int idAutor;
	private Autor autor;
	private Boolean actiu;

	public AutorDetalls() {
	}

	public AutorDetalls(Autor autor) {
		this.autor = autor;
	}

	public AutorDetalls(Autor autor, Boolean actiu) {
		this.autor = autor;
		this.actiu = actiu;
	}

	@GenericGenerator(name = "AutorDetallsIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "autor"))
	@Id
	@GeneratedValue(generator = "AutorDetallsIdGenerator")

	@Column(name = "idAutor", unique = true, nullable = false)
	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	@Column(name = "actiu")
	public Boolean getActiu() {
		return this.actiu;
	}

	public void setActiu(Boolean actiu) {
		this.actiu = actiu;
	}

}
