package Model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Llibres generated by hbm2java
 */
@Entity
@Table(name = "Llibres", catalog = "autors")
public class Llibres implements java.io.Serializable {

	private Integer llibreId;
	private Autor autor;
	private String llibreTitol;
	private Set<Autor> autors = new HashSet<Autor>(0);

	public Llibres() {
	}

	public Llibres(String llibreTitol) {
		this.llibreTitol = llibreTitol;
	}

	public Llibres(Autor autor, String llibreTitol, Set<Autor> autors) {
		this.autor = autor;
		this.llibreTitol = llibreTitol;
		this.autors = autors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "llibreID", unique = true, nullable = false)
	public Integer getLlibreId() {
		return this.llibreId;
	}

	public void setLlibreId(Integer llibreId) {
		this.llibreId = llibreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "autor")
	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	@Column(name = "llibreTitol", nullable = false)
	public String getLlibreTitol() {
		return this.llibreTitol;
	}

	public void setLlibreTitol(String llibreTitol) {
		this.llibreTitol = llibreTitol;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Autor_Llibres", catalog = "autors", joinColumns = {
			@JoinColumn(name = "llibre", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "autor", nullable = false, updatable = false) })
	public Set<Autor> getAutors() {
		return this.autors;
	}

	public void setAutors(Set<Autor> autors) {
		this.autors = autors;
	}

}
